/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trading.view;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import trading.common.NeuralContext;

/**
 *
 * @author pdg
 */
public class LearnPanel extends javax.swing.JPanel {

    /**
     * Creates new form LearnPanel
     */
    public LearnPanel() {
        initComponents();
        
        init();
    }

    /**
     * Neural network related initialization
     */
    private void init() {
        // Init progress bar
        learnProgressBar.setMaximum(NeuralContext.Training.getMaxEpochCount());
        learnProgressBar.setStringPainted(true);
        // Epoch changed
        NeuralContext.Training.addPropertyChangeListener("Epoch", new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                int epoch = (int) evt.getNewValue();
                learnProgressLabel.setText(String.format("Epoch: %d of %d", epoch, NeuralContext.Training.getMaxEpochCount()));
                learnProgressBar.setValue(epoch);
            }
        });
        // Error changed
        NeuralContext.Training.addPropertyChangeListener("Error", new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                lastErrorLabel.setText("Error: " + evt.getNewValue().toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        learnProgressBar = new javax.swing.JProgressBar();
        learnProgressLabel = new javax.swing.JLabel();
        lastErrorLabel = new javax.swing.JLabel();

        learnProgressLabel.setText("Epoch:");

        lastErrorLabel.setText("Last error:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(learnProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(learnProgressLabel)
                            .addComponent(lastErrorLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(learnProgressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(learnProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastErrorLabel)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lastErrorLabel;
    private javax.swing.JProgressBar learnProgressBar;
    private javax.swing.JLabel learnProgressLabel;
    // End of variables declaration//GEN-END:variables
}
