/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trading.view;

import java.awt.Cursor;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.SwingUtilities;
import org.encog.neural.networks.BasicNetwork;
import trading.app.NeuralService;
import trading.common.NeuralContext;

/**
 *
 * @author pdg
 */
public class NetworkPanel extends javax.swing.JPanel {

    /**
     * Creates new form NetworkPanelf
     */
    public NetworkPanel() {
        initComponents();

        init();
    }

    /**
     * Neural network specific init
     */
    public final void init() {
        // Network property change
        NeuralContext.Network.addPropertyChangeListener("Network", new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                BasicNetwork network = (BasicNetwork) evt.getNewValue();
                updateNetworkView(network);
            }
        });
    }

    /**
     * Create and init file chooser
     *
     * @return
     */
    public final JFileChooser getFileChooser() {
        JFileChooser chooser = new JFileChooser();
        // Select files, not directories
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setCurrentDirectory(new File(".\\network"));
        // Set file filter
        chooser.setFileFilter(new FileFilter(){
            private static final String extension = ".network";
            @Override
            public boolean accept(File f) {
                return true;
                //return f.getName().endsWith(extension);
            }

            @Override
            public String getDescription() {
                return extension;
            }
        });

        return chooser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkLayersLabel = new javax.swing.JLabel();
        neuronsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        networkLayersLabel.setText("Layers:");

        neuronsLabel.setText("Neurons: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Neural network summary");

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(networkLayersLabel)
                    .addComponent(neuronsLabel)
                    .addComponent(jLabel1))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(createButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(networkLayersLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(neuronsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(loadButton)))
                .addGap(10, 10, 10)
                .addComponent(saveButton)
                .addGap(18, 18, 18)
                .addComponent(resetButton)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // Create a new one
        NeuralService.createNetwork();
    }//GEN-LAST:event_createButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // Ask for path and load
        JFileChooser openFile = getFileChooser();
        if (openFile.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            // Load
            NeuralService.loadNetwork(openFile.getSelectedFile());
        }
//
    }//GEN-LAST:event_loadButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Ask for path and save
        JFileChooser saveFile = getFileChooser();
        if(saveFile.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            NeuralService.saveNetwork(saveFile.getSelectedFile());
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        NeuralService.resetNetwork();
    }//GEN-LAST:event_resetButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel networkLayersLabel;
    private javax.swing.JLabel neuronsLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    /**
     * Display network info in this panel
     *
     * @param network
     */
    private void updateNetworkView(BasicNetwork network) {
        // Set first part of the texts
        networkLayersLabel.setText("Network layers: ");
        neuronsLabel.setText("Neurons: ");
        if (network == null) {
            return;
        }

        // Set layers label
        networkLayersLabel.setText(networkLayersLabel.getText() + network.getLayerCount());

        // Neurons in layers string like 13, 24, 34...
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < network.getLayerCount(); i++) {
            // Add neurons count to the string
            sb.append(network.getLayerNeuronCount(i));
            if (i < network.getLayerCount() - 1) {
                sb.append(",");
            }
        }
        // Set neurons label
        neuronsLabel.setText(neuronsLabel.getText() + sb.toString());
    }
}
